title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# date format, refer to https://shopify.github.io/liquid/filters/date/ 
# if you want to customize this
devcarpet_theme:
  hero:
    active: true
    title: Responsive Bootstrap 5 Jekyll Template
    description: Welcome in Devcparet Jekyll Theme. You can change this hero banner using _config.yml. You can also replace this image. Study _config to see which other changes could be applied.
  footer_slogan: Done with the help of <a href="https://github.com/bluszcz/jekyll-theme-devcarpet-01">Devcarpet Jekyll Theme</a>.
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # social_links:
  #   twitter: jekyllrb
  #   github:  bluszcz
  #   vimeo: devcarpet
  #   facebook: jekyll
  #   instagram: jekyll
  #   youtube_channel: UCH8bTGji7CZzSExtFGzvdMQ
  #   youtube_channel_name: DevCarpet
  #   youtube: jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-devcarpet-01

collections:
  portfolio:

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-archives


jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

